quarkus.application.name=Canal Digital Energia

# HTTP
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type

# H2 em memória
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:canal_digital;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false

# OpenAPI
quarkus.smallrye-openapi.path=/api/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/api/docs
